germline: Chromosome Class Reference
Chromosome Class Reference
#include <Chromosome.h>
Public Member Functions
Chromosome ()
MarkerSet * getMarkerSet ()
MarkerSet * getMarkerSet (unsigned int)
void addMarkerSet (MarkerSet *ms)
void clear ()
void print (ostream &out, unsigned int, unsigned int)
void print_snps (ostream &out, unsigned int, unsigned int)
Private Attributes
vector< MarkerSet * > chromosome
Detailed Description
Definition at line 11 of file Chromosome.h.
Constructor & Destructor Documentation
Chromosome::Chromosome ()
Definition at line 9 of file Chromosome.cpp.
Member Function Documentation
void Chromosome::addMarkerSet (MarkerSet * ms)
Definition at line 29 of file Chromosome.cpp.
void Chromosome::clear ()
Definition at line 22 of file Chromosome.cpp.
MarkerSet * Chromosome::getMarkerSet ()
Definition at line 12 of file Chromosome.cpp.
References position_ms.
Referenced by Match::approxEqual(), Match::diff(), MatchFactory::hash(), Match::isHom(), operator<<(), Match::scanLeft(), and Match::scanRight().
MarkerSet * Chromosome::getMarkerSet (unsigned int pos)
Definition at line 17 of file Chromosome.cpp.
void Chromosome::print (ostream & out, unsigned int start, unsigned int end)
Definition at line 47 of file Chromosome.cpp.
References position_ms.
void Chromosome::print_snps (ostream & out, unsigned int start, unsigned int end)
Definition at line 34 of file Chromosome.cpp.
References MARKER_SET_SIZE, position_ms, and Individuals::print().
Member Data Documentation
vector<MarkerSet * > Chromosome::chromosome private
Definition at line 41 of file Chromosome.h.
The documentation for this class was generated from the following files:
Chromosome.h
Chromosome.cpp