germline: PolymorphicIndividualsExtractor Class Reference
PolymorphicIndividualsExtractor Class Reference abstract
#include <PolymorphicIndividualsExtractor.h>
Public Member Functions
PolymorphicIndividualsExtractor ()
virtual void getInput ()=0
virtual void loadInput ()=0
virtual void getCompleteMarkerSet (Individual *)=0
virtual void getCompleteMarkerSet (Individual *, Individual *)=0
void setPhased (bool)
bool valid ()
Protected Attributes
Individuals * individualsP
int numberOfMarkers
bool phased
bool valid_flag
Detailed Description
Definition at line 14 of file PolymorphicIndividualsExtractor.h.
Constructor & Destructor Documentation
PolymorphicIndividualsExtractor::PolymorphicIndividualsExtractor ()
Definition at line 12 of file PolymorphicIndividualsExtractor.cpp.
Member Function Documentation
virtual void PolymorphicIndividualsExtractor::getCompleteMarkerSet (Individual *) pure virtual
Implemented in HMIndividualsExtractor, and PEDIndividualsExtractor.
Referenced by MatchesBuilder::readHaploidMarkerSet(), and MatchesBuilder::readMarkerSet().
virtual void PolymorphicIndividualsExtractor::getCompleteMarkerSet (Individual * , Individual *) pure virtual
Implemented in HMIndividualsExtractor, and PEDIndividualsExtractor.
virtual void PolymorphicIndividualsExtractor::getInput () pure virtual
Implemented in HMIndividualsExtractor, and PEDIndividualsExtractor.
virtual void PolymorphicIndividualsExtractor::loadInput () pure virtual
Implemented in HMIndividualsExtractor, and PEDIndividualsExtractor.
Referenced by GERMLINE::mine().
void PolymorphicIndividualsExtractor::setPhased (bool p)
Definition at line 16 of file PolymorphicIndividualsExtractor.cpp.
References phased.
bool PolymorphicIndividualsExtractor::valid ()
Definition at line 21 of file PolymorphicIndividualsExtractor.cpp.
References valid_flag.
Referenced by GERMLINE::mine().
Member Data Documentation
Individuals* PolymorphicIndividualsExtractor::individualsP protected
Definition at line 44 of file PolymorphicIndividualsExtractor.h.
int PolymorphicIndividualsExtractor::numberOfMarkers protected
Definition at line 46 of file PolymorphicIndividualsExtractor.h.
bool PolymorphicIndividualsExtractor::phased protected
Definition at line 48 of file PolymorphicIndividualsExtractor.h.
Referenced by setPhased().
bool PolymorphicIndividualsExtractor::valid_flag protected
Definition at line 50 of file PolymorphicIndividualsExtractor.h.
Referenced by valid().
The documentation for this class was generated from the following files:
PolymorphicIndividualsExtractor.h
PolymorphicIndividualsExtractor.cpp