germline: MatchFactory Class Reference
MatchFactory Class Reference
#include <MatchFactory.h>
Public Member Functions
MatchFactory ()
int size ()
void initialize ()
void hash (Individual *)
void assertShares ()
Private Attributes
map< boost::dynamic_bitset
<>, Share > segments
map< boost::dynamic_bitset
<>, Share >::iterator iter
Detailed Description
Definition at line 13 of file MatchFactory.h.
Constructor & Destructor Documentation
MatchFactory::MatchFactory ()
Definition at line 7 of file MatchFactory.cpp.
Member Function Documentation
void MatchFactory::assertShares ()
Definition at line 10 of file MatchFactory.cpp.
References iter, and segments.
Referenced by MatchesBuilder::matchMarkerSet().
void MatchFactory::hash (Individual * i)
Definition at line 28 of file MatchFactory.cpp.
References ALLOW_HOM, Individual::assertHomozygous(), Individual::getChromosome(), MarkerSet::getMarkerBits(), Chromosome::getMarkerSet(), HAPLOID, HOM_ONLY, iter, MAX_ERR_HET, MAX_ERR_HOM, Individual::numHet(), and segments.
Referenced by MatchesBuilder::matchMarkerSet().
void MatchFactory::initialize ()
Definition at line 24 of file MatchFactory.cpp.
References segments.
Referenced by MatchesBuilder::matchMarkerSet().
int MatchFactory::size ()
Definition at line 18 of file MatchFactory.cpp.
References segments.
Member Data Documentation
map< boost::dynamic_bitset<> , Share >::iterator MatchFactory::iter private
Definition at line 38 of file MatchFactory.h.
Referenced by assertShares(), and hash().
map< boost::dynamic_bitset<> , Share > MatchFactory::segments private
Definition at line 37 of file MatchFactory.h.
Referenced by assertShares(), hash(), initialize(), and size().
The documentation for this class was generated from the following files:
MatchFactory.h
MatchFactory.cpp