germline: SNP Class Reference
SNP Class Reference
#include <SNP.h>
Public Member Functions
SNP ()
int mapNucleotide (char)
string getSNPID () const
long getPhysPos () const
string getChr () const
char getVariant (int i) const
void setSNPID (const string &sid)
void setPhysPos (long pp)
void setVariant (int i, char nt)
void setChr (const string &c)
void setCentimorgan (float cm)
float getCentimorgan ()
void setMarkerNumber (unsigned int)
unsigned int getMarkerNumber ()
Private Attributes
string SNPID
long physPos
float centimorgan
char variant [2]
string chr
short varSet
unsigned int count [2]
unsigned int num
Detailed Description
Definition at line 11 of file SNP.h.
Constructor & Destructor Documentation
SNP::SNP ()
Definition at line 9 of file SNP.cpp.
Member Function Documentation
float SNP::getCentimorgan ()
Definition at line 22 of file SNP.cpp.
Referenced by SNPs::processLegendFile().
string SNP::getChr () const
Definition at line 77 of file SNP.cpp.
Referenced by SNPs::addSNP(), Match::chromosome(), SNPs::getGeneticDistance(), and Match::print().
unsigned int SNP::getMarkerNumber ()
Definition at line 111 of file SNP.cpp.
Referenced by PEDIndividualsExtractor::getCompleteMarkerSet(), HMIndividualsExtractor::loadMarkerSet(), and Match::print().
long SNP::getPhysPos () const
Definition at line 72 of file SNP.cpp.
Referenced by Match::physicalEnd(), Match::physicalStart(), and Match::print().
string SNP::getSNPID () const
Definition at line 65 of file SNP.cpp.
Referenced by SNPs::getGeneticDistance(), GERMLINE::mine(), and Match::print().
char SNP::getVariant (int i) const
Definition at line 83 of file SNP.cpp.
Referenced by MarkerSet::print().
int SNP::mapNucleotide (char nt)
Definition at line 27 of file SNP.cpp.
void SNP::setCentimorgan (float cm)
Definition at line 17 of file SNP.cpp.
Referenced by SNPs::processLegendFile(), and SNPs::processMAPFile().
void SNP::setChr (const string & c)
Definition at line 88 of file SNP.cpp.
Referenced by SNPs::processLegendFile(), and SNPs::processMAPFile().
void SNP::setMarkerNumber (unsigned int i)
Definition at line 106 of file SNP.cpp.
Referenced by SNPs::processLegendFile(), and SNPs::processMAPFile().
void SNP::setPhysPos (long pp)
Definition at line 101 of file SNP.cpp.
Referenced by SNPs::processLegendFile(), and SNPs::processMAPFile().
void SNP::setSNPID (const string & sid)
Definition at line 94 of file SNP.cpp.
Referenced by SNPs::processLegendFile(), and SNPs::processMAPFile().
void SNP::setVariant (int i, char nt)
Definition at line 117 of file SNP.cpp.
Referenced by SNPs::processLegendFile().
Member Data Documentation
float SNP::centimorgan private
Definition at line 73 of file SNP.h.
string SNP::chr private
Definition at line 77 of file SNP.h.
unsigned int SNP::count[2] private
Definition at line 81 of file SNP.h.
unsigned int SNP::num private
Definition at line 83 of file SNP.h.
long SNP::physPos private
Definition at line 71 of file SNP.h.
string SNP::SNPID private
Definition at line 69 of file SNP.h.
char SNP::variant[2] private
Definition at line 75 of file SNP.h.
short SNP::varSet private
Definition at line 79 of file SNP.h.
The documentation for this class was generated from the following files:
SNP.h
SNP.cpp