germline: Match Class Reference
Match Class Reference
#include <Match.h>
Public Member Functions
Match ()
long physicalStart ()
long physicalEnd ()
string chromosome ()
double length ()
bool assertLength ()
Individual * getTarget (Individual *me)
void print (ostream &)
bool approxEqual ()
void erase ()
void extendBack ()
Public Attributes
Individual * node [2]
unsigned int start_ms
unsigned int end_ms
Private Member Functions
int scanLeft (unsigned int ms)
int scanRight (unsigned int ms)
int diff (unsigned int ms)
bool isHom (int n, unsigned int ms)
Detailed Description
Definition at line 13 of file Match.h.
Constructor & Destructor Documentation
Match::Match () inline
Definition at line 17 of file Match.h.
Member Function Documentation
bool Match::approxEqual ()
Definition at line 23 of file Match.cpp.
References ALLOW_HOM, Individual::getChromosome(), MarkerSet::getMarkerBits(), Chromosome::getMarkerSet(), HAP_EXT, HAPLOID, MAX_ERR_HET, MAX_ERR_HOM, and node.
Referenced by Individual::assertShares(), and extendBack().
bool Match::assertLength () inline
Definition at line 29 of file Match.h.
References ALL_SNPS, end_ms, SNPs::getDistance(), MARKER_SET_SIZE, MIN_MATCH_LEN, and start_ms.
string Match::chromosome () inline
Definition at line 24 of file Match.h.
References ALL_SNPS, SNP::getChr(), SNPs::getSNP(), MARKER_SET_SIZE, and start_ms.
int Match::diff (unsigned int ms) private
Definition at line 146 of file Match.cpp.
References Individual::getChromosome(), MarkerSet::getMarkerBits(), Chromosome::getMarkerSet(), and node.
Referenced by print().
void Match::erase ()
void Match::extendBack ()
Definition at line 3 of file Match.cpp.
References approxEqual(), position_ms, and start_ms.
Referenced by Individual::assertHomozygous(), and Share::assertMatches().
Individual* Match::getTarget (Individual * me) inline
Definition at line 35 of file Match.h.
References node.
bool Match::isHom (int n, unsigned int ms) private
Definition at line 156 of file Match.cpp.
References Individual::getChromosome(), MarkerSet::getMarkerBits(), Chromosome::getMarkerSet(), MAX_ERR_HET, MAX_ERR_HOM, and node.
Referenced by print().
double Match::length () inline
Definition at line 25 of file Match.h.
References ALL_SNPS, end_ms, SNPs::getDistance(), MARKER_SET_SIZE, and start_ms.
long Match::physicalEnd () inline
Definition at line 23 of file Match.h.
References ALL_SNPS, end_ms, SNP::getPhysPos(), SNPs::getSNP(), and MARKER_SET_SIZE.
long Match::physicalStart () inline
Definition at line 22 of file Match.h.
References ALL_SNPS, SNP::getPhysPos(), SNPs::getSNP(), MARKER_SET_SIZE, and start_ms.
void Match::print (ostream & fout)
Definition at line 161 of file Match.cpp.
References ALL_SNPS, BINARY_OUT, diff(), end_ms, SNP::getChr(), SNPs::getDistance(), Individual::getID(), SNP::getMarkerNumber(), Individual::getNumericID(), SNP::getPhysPos(), SNPs::getROIStart(), SNPs::getSNP(), SNP::getSNPID(), isHom(), MARKER_SET_SIZE, MIN_MATCH_LEN, node, num_matches, num_sets, scanLeft(), scanRight(), start_ms, and WIN_EXT.
int Match::scanLeft (unsigned int ms) private
Definition at line 73 of file Match.cpp.
References Individual::getChromosome(), MarkerSet::getMarkerBits(), Chromosome::getMarkerSet(), HAP_EXT, HAPLOID, MARKER_SET_SIZE, and node.
Referenced by print().
int Match::scanRight (unsigned int ms) private
Definition at line 110 of file Match.cpp.
References Individual::getChromosome(), MarkerSet::getMarkerBits(), Chromosome::getMarkerSet(), HAP_EXT, HAPLOID, MARKER_SET_SIZE, and node.
Referenced by print().
Member Data Documentation
unsigned int Match::end_ms
Definition at line 20 of file Match.h.
Referenced by Individual::assertHomozygous(), assertLength(), Share::assertMatches(), Individual::assertShares(), Share::createMatch(), length(), physicalEnd(), and print().
Individual* Match::node[2]
Definition at line 19 of file Match.h.
Referenced by approxEqual(), Individual::assertHomozygous(), Share::createMatch(), diff(), getTarget(), isHom(), print(), scanLeft(), and scanRight().
unsigned int Match::start_ms
Definition at line 20 of file Match.h.
Referenced by Individual::assertHomozygous(), assertLength(), chromosome(), Share::createMatch(), extendBack(), length(), physicalStart(), and print().
The documentation for this class was generated from the following files:
Match.h
Match.cpp