germline: Individuals Class Reference
Individuals Class Reference
#include <Individuals.h>
Public Member Functions
Individuals ()
~Individuals ()
void addIndividual (Individual *ind)
Individual * getIndividual (size_t id)
bool more ()
Individual * next ()
void begin ()
size_t size ()
void initialize ()
void print (ostream &)
void freeMatches ()
void freeMarkers ()
Private Member Functions
void permuteMarkerSet (Chromosome *, int, MarkerSet)
Private Attributes
vector< Individual * > pedigree
size_t iter
long sets
Detailed Description
Definition at line 14 of file Individuals.h.
Constructor & Destructor Documentation
Individuals::Individuals ()
Definition at line 9 of file Individuals.cpp.
Individuals::~Individuals ()
Definition at line 12 of file Individuals.cpp.
Member Function Documentation
void Individuals::addIndividual (Individual * ind)
Definition at line 55 of file Individuals.cpp.
References num_samples, and Individual::setNumericID().
void Individuals::begin ()
Definition at line 39 of file Individuals.cpp.
Referenced by MatchesBuilder::matchMarkerSet(), MatchesBuilder::printHaplotypes(), MatchesBuilder::readHaploidMarkerSet(), and MatchesBuilder::readMarkerSet().
void Individuals::freeMarkers ()
Definition at line 28 of file Individuals.cpp.
Referenced by GERMLINE::mine().
void Individuals::freeMatches ()
Definition at line 23 of file Individuals.cpp.
Referenced by GERMLINE::mine().
Individual* Individuals::getIndividual (size_t id) inline
Definition at line 28 of file Individuals.h.
void Individuals::initialize ()
Definition at line 18 of file Individuals.cpp.
bool Individuals::more ()
Definition at line 44 of file Individuals.cpp.
Referenced by MatchesBuilder::matchMarkerSet(), MatchesBuilder::printHaplotypes(), MatchesBuilder::readHaploidMarkerSet(), and MatchesBuilder::readMarkerSet().
Individual * Individuals::next ()
Definition at line 49 of file Individuals.cpp.
Referenced by MatchesBuilder::matchMarkerSet(), MatchesBuilder::printHaplotypes(), MatchesBuilder::readHaploidMarkerSet(), and MatchesBuilder::readMarkerSet().
void Individuals::permuteMarkerSet (Chromosome * , int , MarkerSet) private
void Individuals::print (ostream & out)
Definition at line 33 of file Individuals.cpp.
Referenced by GERMLINE::mine(), and Chromosome::print_snps().
size_t Individuals::size () inline
Definition at line 33 of file Individuals.h.
Member Data Documentation
size_t Individuals::iter private
Definition at line 45 of file Individuals.h.
vector< Individual * > Individuals::pedigree private
Definition at line 44 of file Individuals.h.
long Individuals::sets private
Definition at line 47 of file Individuals.h.
The documentation for this class was generated from the following files:
Individuals.h
Individuals.cpp