germline: MatchesBuilder Class Reference
MatchesBuilder Class Reference
#include <MatchesBuilder.h>
Public Member Functions
MatchesBuilder (PolymorphicIndividualsExtractor *)
void buildMatches ()
void printAllMatches ()
void printHaplotypes (string)
Private Member Functions
void matchAllMarkers ()
void readAllMarkers ()
void matchMarkerSet ()
void readMarkerSet ()
void readHaploidMarkerSet ()
Private Attributes
Individuals * individualsP
MatchFactory matchFactory
PolymorphicIndividualsExtractor * pieP
unsigned int ms_start
unsigned int ms_end
Detailed Description
Definition at line 13 of file MatchesBuilder.h.
Constructor & Destructor Documentation
MatchesBuilder::MatchesBuilder (PolymorphicIndividualsExtractor * pie)
Definition at line 11 of file MatchesBuilder.cpp.
References ALL_SAMPLES, individualsP, and pieP.
Member Function Documentation
void MatchesBuilder::buildMatches ()
Definition at line 18 of file MatchesBuilder.cpp.
References matchAllMarkers(), ms_end, ms_start, num_sets, readAllMarkers(), and SILENT.
Referenced by GERMLINE::mine().
void MatchesBuilder::matchAllMarkers () private
Definition at line 40 of file MatchesBuilder.cpp.
References matchMarkerSet(), ms_end, ms_start, position_ms, and SILENT.
Referenced by buildMatches().
void MatchesBuilder::matchMarkerSet () private
Definition at line 84 of file MatchesBuilder.cpp.
References MatchFactory::assertShares(), Individual::assertShares(), Individuals::begin(), MatchFactory::hash(), individualsP, MatchFactory::initialize(), matchFactory, Individuals::more(), and Individuals::next().
Referenced by matchAllMarkers().
void MatchesBuilder::printAllMatches ()
void MatchesBuilder::printHaplotypes (string fout_name)
Definition at line 28 of file MatchesBuilder.cpp.
References Individuals::begin(), individualsP, Individuals::more(), Individuals::next(), num_sets, and Individual::print().
void MatchesBuilder::readAllMarkers () private
Definition at line 50 of file MatchesBuilder.cpp.
References HAPLOID, ms_end, ms_start, position_ms, readHaploidMarkerSet(), readMarkerSet(), and SILENT.
Referenced by buildMatches().
void MatchesBuilder::readHaploidMarkerSet () private
Definition at line 60 of file MatchesBuilder.cpp.
References Individuals::begin(), PolymorphicIndividualsExtractor::getCompleteMarkerSet(), individualsP, Individuals::more(), Individuals::next(), and pieP.
Referenced by readAllMarkers().
void MatchesBuilder::readMarkerSet () private
Definition at line 73 of file MatchesBuilder.cpp.
References Individuals::begin(), PolymorphicIndividualsExtractor::getCompleteMarkerSet(), individualsP, Individuals::more(), Individuals::next(), and pieP.
Referenced by readAllMarkers().
Member Data Documentation
Individuals* MatchesBuilder::individualsP private
Definition at line 55 of file MatchesBuilder.h.
Referenced by MatchesBuilder(), matchMarkerSet(), printHaplotypes(), readHaploidMarkerSet(), and readMarkerSet().
MatchFactory MatchesBuilder::matchFactory private
Definition at line 57 of file MatchesBuilder.h.
Referenced by matchMarkerSet().
unsigned int MatchesBuilder::ms_end private
Definition at line 61 of file MatchesBuilder.h.
Referenced by buildMatches(), matchAllMarkers(), and readAllMarkers().
unsigned int MatchesBuilder::ms_start private
Definition at line 61 of file MatchesBuilder.h.
Referenced by buildMatches(), matchAllMarkers(), and readAllMarkers().
PolymorphicIndividualsExtractor* MatchesBuilder::pieP private
Definition at line 59 of file MatchesBuilder.h.
Referenced by MatchesBuilder(), readHaploidMarkerSet(), and readMarkerSet().
The documentation for this class was generated from the following files:
MatchesBuilder.h
MatchesBuilder.cpp