germline: HMIndividualsExtractor Class Reference
HMIndividualsExtractor Class Reference
#include <HMIndividualsExtractor.h>
Public Member Functions
HMIndividualsExtractor ()
void getInput ()
void loadInput ()
void getCompleteMarkerSet (Individual *p)
void getCompleteMarkerSet (Individual *p0, Individual *p1)
Public Member Functions inherited from PolymorphicIndividualsExtractor
PolymorphicIndividualsExtractor ()
void setPhased (bool)
bool valid ()
Private Member Functions
void getIndividuals ()
void loadMarkerSet (streamoff offset, MarkerSet **ms)
void stripWhitespace ()
Private Attributes
NucleotideMap inp
string fileLegend
string filePhased
string fileSample
ifstream stream_phased
ifstream stream_sample
int offset_buffer
Additional Inherited Members
Protected Attributes inherited from PolymorphicIndividualsExtractor
Individuals * individualsP
int numberOfMarkers
bool phased
bool valid_flag
Detailed Description
Definition at line 10 of file HMIndividualsExtractor.h.
Constructor & Destructor Documentation
HMIndividualsExtractor::HMIndividualsExtractor ()
Definition at line 11 of file HMIndividualsExtractor.cpp.
Member Function Documentation
void HMIndividualsExtractor::getCompleteMarkerSet (Individual * p) virtual
Implements PolymorphicIndividualsExtractor.
Definition at line 153 of file HMIndividualsExtractor.cpp.
References Individual::addMarkerSet(), Individual::getOffset(), TRANS, and UNTRANS.
void HMIndividualsExtractor::getCompleteMarkerSet (Individual * p0, Individual * p1) virtual
Implements PolymorphicIndividualsExtractor.
Definition at line 114 of file HMIndividualsExtractor.cpp.
References Individual::addMarkerSet(), Individual::getOffset(), and TRANS.
void HMIndividualsExtractor::getIndividuals () private
Definition at line 80 of file HMIndividualsExtractor.cpp.
References HAPLOID, Individual::setID(), and Individual::setOffset().
void HMIndividualsExtractor::getInput () virtual
Implements PolymorphicIndividualsExtractor.
Definition at line 45 of file HMIndividualsExtractor.cpp.
References ALL_SNPS, and SNPs::setFile().
void HMIndividualsExtractor::loadInput () virtual
Implements PolymorphicIndividualsExtractor.
Definition at line 29 of file HMIndividualsExtractor.cpp.
References ALL_SAMPLES, ALL_SNPS, SNPs::beginChromosome(), SNPs::processLegendFile(), and SNPs::size().
void HMIndividualsExtractor::loadMarkerSet (streamoff offset, MarkerSet ** ms) private
Definition at line 128 of file HMIndividualsExtractor.cpp.
References ALL_SNPS, SNPs::currentSize(), SNP::getMarkerNumber(), SNPs::getROIStart(), MARKER_SET_SIZE, position_ms, and MarkerSet::set().
void HMIndividualsExtractor::stripWhitespace () private
Definition at line 14 of file HMIndividualsExtractor.cpp.
Member Data Documentation
string HMIndividualsExtractor::fileLegend private
Definition at line 36 of file HMIndividualsExtractor.h.
string HMIndividualsExtractor::filePhased private
Definition at line 36 of file HMIndividualsExtractor.h.
string HMIndividualsExtractor::fileSample private
Definition at line 36 of file HMIndividualsExtractor.h.
NucleotideMap HMIndividualsExtractor::inp private
Definition at line 35 of file HMIndividualsExtractor.h.
int HMIndividualsExtractor::offset_buffer private
Definition at line 38 of file HMIndividualsExtractor.h.
ifstream HMIndividualsExtractor::stream_phased private
Definition at line 37 of file HMIndividualsExtractor.h.
ifstream HMIndividualsExtractor::stream_sample private
Definition at line 37 of file HMIndividualsExtractor.h.
The documentation for this class was generated from the following files:
HMIndividualsExtractor.h
HMIndividualsExtractor.cpp