germline: Individual Class Reference
Individual Class Reference
#include <Individual.h>
Public Member Functions
void reserveMemory ()
void addShare (Share *)
void assertShares ()
void assertHomozygous ()
list< Share * > & getShareList ()
void freeMatches ()
Match * getMatch (size_t)
void deleteMatch (size_t)
void clearMatch (size_t)
void addMatch (size_t, Match *)
void print (ostream &, long, long)
bool isHeterozygous ()
bool isHeterozygous (int i)
int numHet ()
Individual ()
~Individual ()
string getID () const
void setOffset (streamoff)
streamoff getOffset ()
Chromosome * getChromosome (int)
Chromosome * getAlternateChromosome (Chromosome *)
void setID (string id)
void setNumericID (unsigned int id)
unsigned int getNumericID ()
void addMarkerSet (int, MarkerSet *ms)
void clearMarkers ()
Private Attributes
string ID
unsigned int numeric_id
Chromosome * h
streamoff offset
Match ** all_matches
Detailed Description
Definition at line 33 of file Individual.h.
Constructor & Destructor Documentation
Individual::Individual ()
Definition at line 7 of file Individual.cpp.
References HAPLOID.
Individual::~Individual ()
Definition at line 13 of file Individual.cpp.
Member Function Documentation
void Individual::addMarkerSet (int ct, MarkerSet * ms)
Definition at line 177 of file Individual.cpp.
References HAPLOID.
Referenced by PEDIndividualsExtractor::getCompleteMarkerSet(), and HMIndividualsExtractor::getCompleteMarkerSet().
void Individual::addMatch (size_t id, Match * m)
Definition at line 81 of file Individual.cpp.
void Individual::addShare (Share *)
void Individual::assertHomozygous ()
Definition at line 30 of file Individual.cpp.
References Match::end_ms, Match::extendBack(), Match::node, position_ms, and Match::start_ms.
Referenced by MatchFactory::hash().
void Individual::assertShares ()
Definition at line 50 of file Individual.cpp.
References Match::approxEqual(), Match::end_ms, num_samples, and position_ms.
Referenced by MatchesBuilder::matchMarkerSet().
void Individual::clearMarkers ()
Definition at line 170 of file Individual.cpp.
References HAPLOID.
void Individual::clearMatch (size_t id)
Definition at line 67 of file Individual.cpp.
void Individual::deleteMatch (size_t id)
Definition at line 71 of file Individual.cpp.
References MATCH_FILE.
void Individual::freeMatches ()
Definition at line 19 of file Individual.cpp.
References num_samples.
Chromosome * Individual::getAlternateChromosome (Chromosome * c)
Definition at line 138 of file Individual.cpp.
References HAPLOID.
Chromosome * Individual::getChromosome (int ct)
Definition at line 147 of file Individual.cpp.
References HAPLOID.
Referenced by Match::approxEqual(), Match::diff(), MatchFactory::hash(), Match::isHom(), operator<<(), Match::scanLeft(), and Match::scanRight().
string Individual::getID () const
Definition at line 133 of file Individual.cpp.
Referenced by operator<<(), and Match::print().
Match * Individual::getMatch (size_t id)
Definition at line 25 of file Individual.cpp.
unsigned int Individual::getNumericID ()
Definition at line 154 of file Individual.cpp.
Referenced by Match::print().
streamoff Individual::getOffset ()
Definition at line 127 of file Individual.cpp.
Referenced by PEDIndividualsExtractor::getCompleteMarkerSet(), and HMIndividualsExtractor::getCompleteMarkerSet().
list<Share*>& Individual::getShareList ()
bool Individual::isHeterozygous ()
Definition at line 110 of file Individual.cpp.
References HAPLOID.
bool Individual::isHeterozygous (int i)
Definition at line 116 of file Individual.cpp.
References HAPLOID.
int Individual::numHet ()
Definition at line 104 of file Individual.cpp.
References HAPLOID.
Referenced by MatchFactory::hash().
void Individual::print (ostream & out, long start, long end)
Match Tracking
Definition at line 92 of file Individual.cpp.
References HAPLOID.
Referenced by MatchesBuilder::printHaplotypes().
void Individual::reserveMemory ()
Match Tracking
Definition at line 86 of file Individual.cpp.
References num_samples.
void Individual::setID (string id)
Definition at line 165 of file Individual.cpp.
Referenced by HMIndividualsExtractor::getIndividuals(), and PEDIndividualsExtractor::getIndividuals().
void Individual::setNumericID (unsigned int id)
Definition at line 159 of file Individual.cpp.
Referenced by Individuals::addIndividual().
void Individual::setOffset (streamoff o)
Definition at line 122 of file Individual.cpp.
Referenced by HMIndividualsExtractor::getIndividuals(), and PEDIndividualsExtractor::getIndividuals().
Member Data Documentation
Match** Individual::all_matches private
Definition at line 107 of file Individual.h.
Chromosome* Individual::h private
Definition at line 103 of file Individual.h.
string Individual::ID private
Definition at line 100 of file Individual.h.
unsigned int Individual::numeric_id private
Definition at line 101 of file Individual.h.
streamoff Individual::offset private
Definition at line 105 of file Individual.h.
The documentation for this class was generated from the following files:
Individual.h
Individual.cpp