germline: MarkerSet Class Reference
MarkerSet Class Reference
#include <MarkerSet.h>
Public Member Functions
MarkerSet ()
MarkerSet (const MarkerSet &)
void clear ()
void set (int, bool)
void print (ostream &)
void print (ostream &, unsigned int, unsigned int)
boost::dynamic_bitset & getMarkerBits ()
bool getMarker (int index) const
bool equal (MarkerSet *ms)
int diff (MarkerSet *) const
Private Attributes
boost::dynamic_bitset markers
Detailed Description
Definition at line 12 of file MarkerSet.h.
Constructor & Destructor Documentation
MarkerSet::MarkerSet ()
Definition at line 9 of file MarkerSet.cpp.
References MARKER_SET_SIZE.
MarkerSet::MarkerSet (const MarkerSet & copy)
Definition at line 14 of file MarkerSet.cpp.
References markers.
Member Function Documentation
void MarkerSet::clear ()
Definition at line 19 of file MarkerSet.cpp.
int MarkerSet::diff (MarkerSet * ms) const
Definition at line 61 of file MarkerSet.cpp.
References markers.
bool MarkerSet::equal (MarkerSet * ms)
Definition at line 55 of file MarkerSet.cpp.
References markers.
bool MarkerSet::getMarker (int index) const
Definition at line 31 of file MarkerSet.cpp.
Referenced by operator<<().
boost::dynamic_bitset & MarkerSet::getMarkerBits ()
Definition at line 25 of file MarkerSet.cpp.
Referenced by Match::approxEqual(), Match::diff(), MatchFactory::hash(), Match::isHom(), Match::scanLeft(), and Match::scanRight().
void MarkerSet::print (ostream & out)
Definition at line 49 of file MarkerSet.cpp.
References MARKER_SET_SIZE.
void MarkerSet::print (ostream & out, unsigned int start, unsigned int end)
Definition at line 41 of file MarkerSet.cpp.
References ALL_SNPS, SNPs::currentSize(), SNPs::getSNP(), SNP::getVariant(), MARKER_SET_SIZE, and position_ms.
void MarkerSet::set (int index, bool bit)
Definition at line 36 of file MarkerSet.cpp.
Referenced by HMIndividualsExtractor::loadMarkerSet().
Member Data Documentation
boost::dynamic_bitset MarkerSet::markers private
Definition at line 48 of file MarkerSet.h.
Referenced by diff(), equal(), and MarkerSet().
The documentation for this class was generated from the following files:
MarkerSet.h
MarkerSet.cpp