germline: Share Class Reference
Share Class Reference
#include <Individual.h>
Public Member Functions
Share (Individual *)
void add (Individual *)
void assertMatches ()
Private Member Functions
Match * createMatch (Individual *c1, Individual *c2)
Private Attributes
list< Individual * > matches
Detailed Description
Definition at line 20 of file Individual.h.
Constructor & Destructor Documentation
Share::Share (Individual * cip)
Definition at line 4 of file Share.cpp.
References add().
Member Function Documentation
void Share::add (Individual * cip)
Definition at line 52 of file Share.cpp.
References matches.
Referenced by Share().
void Share::assertMatches ()
Definition at line 9 of file Share.cpp.
References createMatch(), Match::end_ms, Match::extendBack(), matches, and position_ms.
Match * Share::createMatch (Individual * c1, Individual * c2) private
Definition at line 41 of file Share.cpp.
References Match::end_ms, Match::node, position_ms, and Match::start_ms.
Referenced by assertMatches().
Member Data Documentation
list< Individual * > Share::matches private
Definition at line 29 of file Individual.h.
Referenced by add(), and assertMatches().
The documentation for this class was generated from the following files:
Individual.h
Share.cpp