germline: GERMLINE Class Reference
GERMLINE Class Reference
#include <GERMLINE.h>
Public Member Functions
GERMLINE ()
void mine (string params)
Private Attributes
InputManager inputManager
Detailed Description
Definition at line 13 of file GERMLINE.h.
Constructor & Destructor Documentation
GERMLINE::GERMLINE ()
Definition at line 16 of file GERMLINE.cpp.
Member Function Documentation
void GERMLINE::mine (string params)
Definition at line 20 of file GERMLINE.cpp.
References ALL_SAMPLES, ALL_SNPS, SNPs::beginChromosome(), BINARY_OUT, MatchesBuilder::buildMatches(), SNPs::currentSize(), DEBUG, Individuals::freeMarkers(), Individuals::freeMatches(), SNPs::getROIEnd(), SNPs::getROIStart(), SNP::getSNPID(), PolymorphicIndividualsExtractor::loadInput(), MARKER_SET_SIZE, MATCH_FILE, MAX_ERR_HET, MAX_ERR_HOM, MIN_MATCH_LEN, SNPs::moreChromosome(), SNPs::nextChromosome(), num_matches, num_samples, num_sets, Individuals::print(), SNPs::print(), ROI, SILENT, and PolymorphicIndividualsExtractor::valid().
Referenced by main().
Member Data Documentation
InputManager GERMLINE::inputManager private
Definition at line 32 of file GERMLINE.h.
The documentation for this class was generated from the following files:
GERMLINE.h
GERMLINE.cpp