germline: PEDIndividualsExtractor Class Reference
PEDIndividualsExtractor Class Reference
#include <PEDIndividualsExtractor.h>
Public Member Functions
PEDIndividualsExtractor ()
void getInput ()
void loadInput ()
void getCompleteMarkerSet (Individual *p)
void getCompleteMarkerSet (Individual *p0, Individual *p1)
Public Member Functions inherited from PolymorphicIndividualsExtractor
PolymorphicIndividualsExtractor ()
void setPhased (bool)
bool valid ()
Private Member Functions
void getIndividuals ()
void stripWhitespace ()
void readMarkerSet (MarkerSet **)
Private Attributes
string ped_file
string map_file
ifstream stream
NucleotideMap inp
Additional Inherited Members
Protected Attributes inherited from PolymorphicIndividualsExtractor
Individuals * individualsP
int numberOfMarkers
bool phased
bool valid_flag
Detailed Description
Definition at line 10 of file PEDIndividualsExtractor.h.
Constructor & Destructor Documentation
PEDIndividualsExtractor::PEDIndividualsExtractor ()
Definition at line 9 of file PEDIndividualsExtractor.cpp.
Member Function Documentation
void PEDIndividualsExtractor::getCompleteMarkerSet (Individual * p) virtual
Implements PolymorphicIndividualsExtractor.
Definition at line 97 of file PEDIndividualsExtractor.cpp.
References Individual::addMarkerSet(), ALL_SNPS, SNP::getMarkerNumber(), Individual::getOffset(), SNPs::getROIStart(), MARKER_SET_SIZE, position_ms, TRANS, and UNTRANS.
void PEDIndividualsExtractor::getCompleteMarkerSet (Individual * p0, Individual * p1) virtual
Implements PolymorphicIndividualsExtractor.
Definition at line 126 of file PEDIndividualsExtractor.cpp.
References Individual::addMarkerSet(), ALL_SNPS, SNP::getMarkerNumber(), Individual::getOffset(), SNPs::getROIStart(), MARKER_SET_SIZE, position_ms, and TRANS.
void PEDIndividualsExtractor::getIndividuals () private
Definition at line 71 of file PEDIndividualsExtractor.cpp.
References HAPLOID, Individual::setID(), and Individual::setOffset().
void PEDIndividualsExtractor::getInput () virtual
Implements PolymorphicIndividualsExtractor.
Definition at line 45 of file PEDIndividualsExtractor.cpp.
References ALL_SNPS, and SNPs::setFile().
void PEDIndividualsExtractor::loadInput () virtual
Implements PolymorphicIndividualsExtractor.
Definition at line 27 of file PEDIndividualsExtractor.cpp.
References ALL_SAMPLES, ALL_SNPS, SNPs::beginChromosome(), SNPs::processMAPFile(), and SNPs::size().
void PEDIndividualsExtractor::readMarkerSet (MarkerSet ** ms) private
Definition at line 110 of file PEDIndividualsExtractor.cpp.
References ALL_SNPS, SNPs::currentSize(), SNPs::mapNucleotideToBinary(), MARKER_SET_SIZE, and position_ms.
void PEDIndividualsExtractor::stripWhitespace () private
Definition at line 12 of file PEDIndividualsExtractor.cpp.
Member Data Documentation
NucleotideMap PEDIndividualsExtractor::inp private
Definition at line 43 of file PEDIndividualsExtractor.h.
string PEDIndividualsExtractor::map_file private
Definition at line 38 of file PEDIndividualsExtractor.h.
string PEDIndividualsExtractor::ped_file private
Definition at line 36 of file PEDIndividualsExtractor.h.
ifstream PEDIndividualsExtractor::stream private
Definition at line 40 of file PEDIndividualsExtractor.h.
The documentation for this class was generated from the following files:
PEDIndividualsExtractor.h
PEDIndividualsExtractor.cpp