germline: SNPs Class Reference
SNPs Class Reference
#include <SNPs.h>
Public Member Functions
SNPs ()
unsigned int size ()
unsigned int currentSize ()
void setROI (string rsid[2])
SNP getROIStart ()
SNP getROIEnd ()
string getChromosome ()
void loadGeneticDistanceMap (string)
void setGeneticDistances ()
SNP getSNP (unsigned int markerPosition) const
float getDistance (unsigned int, unsigned int)
float getDistance (unsigned int, unsigned int, bool &genetic)
char getVariant (unsigned int index, int variant) const
int mapNucleotideToBinary (char nt, unsigned int index)
void processLegendFile ()
void processMAPFile ()
bool setFile (string)
void print (ostream &)
void beginChromosome ()
bool moreChromosome ()
void nextChromosome ()
Private Member Functions
void stripWhiteSpace (ifstream &stream)
float getGeneticDistance (SNP)
void addSNP (SNP &)
Private Attributes
string info
ifstream s
unsigned int full_size
map< string, map< string, float > > cm_map
map< string, vector< SNP > > genome
map< string, vector< SNP >
>::iterator chromosome
map< string, vector< SNP >
>::iterator ROI_chromosome
list< map< string, vector< SNP >
>::iterator > chr_list
NucleotideMap cnm
string ROI_id [2]
int ROI_snp [2]
Detailed Description
Definition at line 18 of file SNPs.h.
Constructor & Destructor Documentation
SNPs::SNPs ()
Definition at line 9 of file SNPs.cpp.
Member Function Documentation
void SNPs::addSNP (SNP & new_snp) private
Definition at line 242 of file SNPs.cpp.
References chr_list, chromosome, genome, and SNP::getChr().
Referenced by processLegendFile(), and processMAPFile().
void SNPs::beginChromosome ()
Definition at line 30 of file SNPs.cpp.
References ROI.
Referenced by PEDIndividualsExtractor::loadInput(), HMIndividualsExtractor::loadInput(), and GERMLINE::mine().
unsigned int SNPs::currentSize ()
Definition at line 12 of file SNPs.cpp.
References ROI.
Referenced by HMIndividualsExtractor::loadMarkerSet(), GERMLINE::mine(), MarkerSet::print(), and PEDIndividualsExtractor::readMarkerSet().
string SNPs::getChromosome ()
Definition at line 25 of file SNPs.cpp.
float SNPs::getDistance (unsigned int start_marker, unsigned int end_marker)
Definition at line 51 of file SNPs.cpp.
Referenced by Match::assertLength(), Match::length(), and Match::print().
float SNPs::getDistance (unsigned int start_marker, unsigned int end_marker, bool & genetic)
Definition at line 57 of file SNPs.cpp.
float SNPs::getGeneticDistance (SNP cur) private
Definition at line 301 of file SNPs.cpp.
References cm_map, SNP::getChr(), and SNP::getSNPID().
Referenced by processLegendFile(), and processMAPFile().
SNP SNPs::getROIEnd ()
Definition at line 319 of file SNPs.cpp.
References chromosome, ROI, ROI_chromosome, and ROI_snp.
Referenced by GERMLINE::mine().
SNP SNPs::getROIStart ()
Definition at line 313 of file SNPs.cpp.
References chromosome, ROI, ROI_chromosome, and ROI_snp.
Referenced by PEDIndividualsExtractor::getCompleteMarkerSet(), HMIndividualsExtractor::loadMarkerSet(), GERMLINE::mine(), and Match::print().
SNP SNPs::getSNP (unsigned int markerPosition) const
Definition at line 134 of file SNPs.cpp.
Referenced by Match::chromosome(), Match::physicalEnd(), Match::physicalStart(), MarkerSet::print(), and Match::print().
char SNPs::getVariant (unsigned int index, int variant) const
Definition at line 146 of file SNPs.cpp.
References A, and chromosome.
void SNPs::loadGeneticDistanceMap (string f)
Definition at line 115 of file SNPs.cpp.
Referenced by main().
int SNPs::mapNucleotideToBinary (char nt, unsigned int index)
Definition at line 180 of file SNPs.cpp.
References chromosome.
Referenced by PEDIndividualsExtractor::readMarkerSet().
bool SNPs::moreChromosome ()
Definition at line 35 of file SNPs.cpp.
Referenced by GERMLINE::mine().
void SNPs::nextChromosome ()
Definition at line 39 of file SNPs.cpp.
Referenced by GERMLINE::mine().
void SNPs::print (ostream & out)
Definition at line 167 of file SNPs.cpp.
References chr_list.
Referenced by GERMLINE::mine().
void SNPs::processLegendFile ()
Definition at line 258 of file SNPs.cpp.
References addSNP(), chromosome, full_size, SNP::getCentimorgan(), getGeneticDistance(), ROI, ROI_chromosome, ROI_id, ROI_snp, s, SNP::setCentimorgan(), SNP::setChr(), setGeneticDistances(), SNP::setMarkerNumber(), SNP::setPhysPos(), SNP::setSNPID(), SNP::setVariant(), and SILENT.
Referenced by HMIndividualsExtractor::loadInput().
void SNPs::processMAPFile ()
Definition at line 191 of file SNPs.cpp.
References addSNP(), chromosome, full_size, getGeneticDistance(), ROI, ROI_chromosome, ROI_id, ROI_snp, s, SNP::setCentimorgan(), SNP::setChr(), setGeneticDistances(), SNP::setMarkerNumber(), SNP::setPhysPos(), and SNP::setSNPID().
Referenced by PEDIndividualsExtractor::loadInput().
bool SNPs::setFile (string f)
Definition at line 44 of file SNPs.cpp.
Referenced by PEDIndividualsExtractor::getInput(), and HMIndividualsExtractor::getInput().
void SNPs::setGeneticDistances ()
Definition at line 74 of file SNPs.cpp.
Referenced by processLegendFile(), and processMAPFile().
void SNPs::setROI (string rsid[2])
Definition at line 185 of file SNPs.cpp.
References ROI_id.
Referenced by main().
unsigned int SNPs::size ()
Definition at line 20 of file SNPs.cpp.
Referenced by PEDIndividualsExtractor::loadInput(), and HMIndividualsExtractor::loadInput().
void SNPs::stripWhiteSpace (ifstream & stream) private
Definition at line 326 of file SNPs.cpp.
Member Data Documentation
list< map< string , vector<SNP> >::iterator > SNPs::chr_list private
Definition at line 99 of file SNPs.h.
Referenced by addSNP(), and print().
map< string , vector<SNP> >::iterator SNPs::chromosome private
Definition at line 96 of file SNPs.h.
Referenced by addSNP(), getROIEnd(), getROIStart(), getVariant(), mapNucleotideToBinary(), processLegendFile(), and processMAPFile().
map< string , map< string , float > > SNPs::cm_map private
Definition at line 92 of file SNPs.h.
Referenced by getGeneticDistance().
NucleotideMap SNPs::cnm private
Definition at line 101 of file SNPs.h.
unsigned int SNPs::full_size private
Definition at line 89 of file SNPs.h.
Referenced by processLegendFile(), and processMAPFile().
map< string , vector<SNP> > SNPs::genome private
Definition at line 95 of file SNPs.h.
Referenced by addSNP().
string SNPs::info private
Definition at line 87 of file SNPs.h.
map< string , vector<SNP> >::iterator SNPs::ROI_chromosome private
Definition at line 97 of file SNPs.h.
Referenced by getROIEnd(), getROIStart(), processLegendFile(), and processMAPFile().
string SNPs::ROI_id[2] private
Definition at line 103 of file SNPs.h.
Referenced by processLegendFile(), processMAPFile(), and setROI().
int SNPs::ROI_snp[2] private
Definition at line 104 of file SNPs.h.
Referenced by getROIEnd(), getROIStart(), processLegendFile(), and processMAPFile().
ifstream SNPs::s private
Definition at line 88 of file SNPs.h.
Referenced by processLegendFile(), and processMAPFile().
The documentation for this class was generated from the following files:
SNPs.h
SNPs.cpp